main: root

root:
  _map:
    apiVersion: apiVersion
    kind: kind
  _mapFacultative:
    metadata: metadata
  _mapOf: { string: string }

kind: string

apiVersion: string

metadata:
  _mapOf: { string: string }

