name: Clean

on:
  schedule:
    - cron: '0 1 * * *'

jobs:
  del_runs:
    name: Delete workflow runs and cache
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 7
          keep_minimum_runs: 0
          delete_run_by_conclusion_pattern: All
      - name: Delete cache
        uses: MyAlbum/purge-cache@v1
        with:
          max-age: 604800 # Cache max 7 days since last use
